# Generated by Django 5.1.1 on 2024-09-29 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='phone Model')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('screen_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Screen Size')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.country', verbose_name='Origin Country')),
            ],
        ),
    ]
