# Generated by Django 5.1.1 on 2024-09-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_brand_created_at_brand_updated_at_country_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phone.brand', verbose_name='Brand'),
        ),
    ]
