# Generated by Django 5.1.1 on 2024-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_phone_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is Active'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is Active'),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is Active'),
        ),
    ]
